#Set up postgres for convenience local dev, just run bootRun.
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_core_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: